# General settings
seed: 42
device: cuda

# Data settings
data_dim: 2
distribution: mixed  # Options: gaussian, skewed, heavy_tail, mixed, asymmetric_laplace
skewness: 2.0
tail_weight: 3.0
n_samples_train: 10000
n_samples_val: 2000

# Model settings
model: alvae  # Options: gaussian_vae, student_t_vae, vlvae, pvae, alvae
encoder_type: mlp
decoder_type: mlp
latent_dim: 10
activation: relu  # Options: relu, leaky_relu, swish
output_activation: null  # Options: null, sigmoid, tanh

# Architecture
encoder_hidden_dims: [256, 128]
decoder_hidden_dims: [128, 256]

# For convolutional models
input_channels: 1
input_size: 28

# Training settings
num_epochs: 100
batch_size: 128
learning_rate: 0.001
weight_decay: 0.0
early_stopping_patience: 20
vis_frequency: 10

# Loss settings
beta: 1.0  # KL weight for beta-VAE

# Model-specific settings
# For VLVAE
num_iterations: 5

# For Poisson VAE
temperature: 1.0

# For Asymmetric Laplace VAE
mmd_weight: 1.0

# Logging
num_workers: 0